name: SaaS Update PR
on:
  pull_request_target:
    types:
      - closed
    branches:
      - 6.[0-9]+.[0-9]+.x

jobs:
  create_saas_update_pr:
    name: Create SaaS Update PR
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged && github.repository == 'shopwell/shopwell' }}
    permissions:
      id-token: write
    steps:
      - uses: shopwell-shop/github-actions/update-saas-refs@51511121da3f6239e5df7cd307428aac88d728d1
