name: Sync Repo

on:
  push:
    branches:
      - trunk
      - 6.[0-9]*.x
      - 6.[0-9]*.[0-9]*.x
  workflow_call:

jobs:
  sync:
    runs-on: ubuntu-24.04
    if: github.repository == 'shopwell/shopwell'
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: shopwell/octo-sts-action@main
        id: sts-shopwell-private
        with:
          scope: shopwell
          identity: ShopwellPrivateSync

      - name: Push to private fork
        run: |
          git config "http.https://github.com/shopwell-shop/shopwell-private.git/.extraheader" "AUTHORIZATION: basic $(echo -n "x-access-token:${{ steps.sts-shopwell-private.outputs.token }}" | base64 -w0)"
          git remote add private https://github.com/shopwell-shop/shopwell-private.git
          git fetch private
          git push -f private ${{ github.ref }}

